version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: |
          docker --version
          echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
          docker build . -t dexels/fscrawler_2.7snap:${CIRCLE_BUILD_NUM}
          docker push dexels/fscrawler_2.7snap:${CIRCLE_BUILD_NUM}


workflows:
  version: 2
  workflow:
    jobs:
    - build:
        context:
        - dexels_docker_hub
